### ISSUE TITLE
Filename with * is not Windows-friendly

### ISSUE THREAD

**Issue by CherryKatatonic** [TechtonicAcademy/Initial-Pre-Work#4]
**Filename of Module 6 - Lesson 24 contains an asterisk which makes it incompatible with Windows file system.**

**Received error upon cloning repo:**

> error: unable to create file 6-Introduction-to-the-ES6-Challenges/24-Use-*-to-Import-Everything-from-a-File.js: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

`git checkout -f HEAD` fails with similar error "Invalid argument"

**Workaround:**
Remove file from repo and commit replacement file with Windows-friendly filename

Reference to Windows filename compliance: [https://docs.microsoft.com/en-us/windows/desktop/msi/filename](https://docs.microsoft.com/en-us/windows/desktop/msi/filename)

**Comment by ShambreSW** [comment]
This issue has been fixed by replacing the * symbol with the word asterisk.  Thanks for the heads up!
